trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  azureSubscription: 'Azure subscription 1(c43a497b-cb7e-4545-b2ea-54ed178a58d6)'
  webAppName: 'ocsAuth'

stages:

# ==========================================
# BUILD STAGE
# ==========================================
- stage: Build
  displayName: Build Application

  jobs:
  - job: Build
    displayName: Restore Build Test Publish

    steps:

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      displayName: Restore Packages
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      displayName: Build Solution
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: >
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package
          /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true
          /p:PackageLocation="$(Build.ArtifactStagingDirectory)"

    - task: VSTest@2
      displayName: Run Tests
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# ==========================================
# DEPLOY STAGE
# ==========================================
- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build

  jobs:
  - deployment: DeployWebApp
    displayName: Deploy to Azure App Service

    environment: 'Production'

    strategy:
      runOnce:
        deploy:

          steps:

          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: Deploy to Azure Web App
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'