trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  azureSubscription: 'Azure subscription 1(c43a497b-cb7e-4545-b2ea-54ed178a58d6)'
  webAppName: 'ocsinventory'

stages:

# ======================================================
# BUILD STAGE
# ======================================================
- stage: Build
  displayName: Build Application

  jobs:
  - job: Build
    displayName: Restore Build Test Publish

    steps:

    # Install NuGet
    - task: NuGetToolInstaller@1

    # Restore Packages
    - task: NuGetCommand@2
      displayName: Restore Packages
      inputs:
        restoreSolution: '$(solution)'

    # Build and Publish Website
    - task: VSBuild@1
      displayName: Build Solution
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: >
          /p:DeployOnBuild=true
          /p:WebPublishMethod=FileSystem
          /p:DeleteExistingFiles=true
          /p:publishUrl="$(Build.ArtifactStagingDirectory)\publish"

    # Run Tests
    - task: VSTest@2
      displayName: Run Tests
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    # Archive Published Files
    - task: ArchiveFiles@2
      displayName: Create Deployment ZIP
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\publish'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)\WebApp.zip'
        replaceExistingArchive: true

    # Publish Artifacts
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# ======================================================
# DEPLOY STAGE
# ======================================================
- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build

  jobs:
  - deployment: DeployWebApp
    displayName: Deploy to Azure App Service

    environment: 'Production'

    strategy:
      runOnce:
        deploy:

          steps:

          # Download Artifact
          - download: current
            artifact: drop

         # Deploy to Azure App Service Slot
          - task: AzureWebApp@1
            displayName: Deploy to Azure Web App Staging Slot
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(webAppName)'
              deployToSlotOrASE: true
              resourceGroupName: 'ocsauth_group'
              slotName: 'staging'
              package: '$(Pipeline.Workspace)/drop/WebApp.zip'