trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

  # Azure DevOps Service Connection
  azureSubscription: 'Azure subscription 1(c43a497b-cb7e-4545-b2ea-54ed178a58d6)'

  # Azure App Service Name
  webAppName: 'ocsAuth'

stages:

# ======================================================
# BUILD STAGE
# ======================================================
- stage: Build
  displayName: Build Application

  jobs:
  - job: Build
    displayName: Restore Build Test Publish

    steps:

    # Install NuGet
    - task: NuGetToolInstaller@1

    # Restore NuGet Packages
    - task: NuGetCommand@2
      displayName: Restore Packages
      inputs:
        restoreSolution: '$(solution)'

    # Build Solution and Create ZIP Package
    - task: VSBuild@1
      displayName: Build Solution
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: >
          /p:DeployOnBuild=true
          /p:WebPublishMethod=Package
          /p:PackageAsSingleFile=true
          /p:SkipInvalidConfigurations=true
          /p:DesktopBuildPackageLocation="$(Build.ArtifactStagingDirectory)\WebApp.zip"
          /p:DeployIisAppPath="Default Web Site"

    # Run Tests
    - task: VSTest@2
      displayName: Run Tests
      inputs:
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    # Publish Build Artifacts
    - task: PublishBuildArtifacts@1
      displayName: Publish Build Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

# ======================================================
# DEPLOY STAGE
# ======================================================
- stage: Deploy
  displayName: Deploy to Azure
  dependsOn: Build

  jobs:
  - deployment: DeployWebApp
    displayName: Deploy to Azure App Service

    environment: 'Production'

    strategy:
      runOnce:
        deploy:

          steps:

          # Download Build Artifact
          - download: current
            artifact: drop

          # Deploy to Azure App Service
          - task: AzureWebApp@1
            displayName: Deploy to Azure Web App
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/WebApp.zip'